Added basic pause menu functionality
RubyNova/MobileSpacePuzzleGame pull request #8
Opened 2019-11-15 00:37 UTC by Rokkii

Pause menu added to test scene 2

2019-11-15 22:35 UTC, RubyNova requested changes
Some formatting and structural concerns, also the commands a little bit out-of-place IMO but you can leave those alone if you want.

2019-11-15 22:35 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +    public static bool GamePaused = false; /*Declare GamePaused variable, initially set to false*/
`static` is innately evil. Please rework this to not be static. Also public fields are bad practice. Please revise into a full or auto property.

2019-11-15 22:35 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +        if (Input.GetKeyDown(KeyCode.Escape))
Invert this `if` statement please.

2019-11-15 22:35 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +    public GameObject pauseMenuUI;
Please rework this public field.

2019-11-15 22:35 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +    void Update()
Accessor is missing. Please add it.

2019-11-16 01:08 UTC, Rokkii reviewed
Code fixes - review request

2019-11-16 01:30 UTC, RubyNova requested changes

2019-11-16 01:30 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
>      public GameObject pauseMenuUI;
This is not resolved.

2019-11-16 01:30 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +        if (!Input.GetKeyDown(KeyCode.Escape))
This is not resolved.

2019-11-16 02:35 UTC, RubyNova requested changes

2019-11-16 02:35 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +    private void Resume()
This attribute does nothing for methods. Clue's in the name `SerializeField`. Methods are not fields. Please remove.

2019-11-16 02:35 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +    private void Pause()
Please remove attribute.

2019-11-18 23:11 UTC, RubyNova requested changes
very minor adjustments then good to merge.

2019-11-18 23:11 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +    private bool GamePaused = false; /*Declare GamePaused variable, initially set to false*/
This should be name `_likeThis` not `LikeThis`.

2019-11-18 23:11 UTC, RubyNova commented on UnityClient/Assets/Scripts/PauseMenu.cs
> +    private GameObject pauseMenuUI;
Missing underscore prefix for a private field. Please fix.

2019-11-27 23:39 UTC, RubyNova approved these changes
LGTM.

2019-11-27 23:39 UTC, merged